### ISSUE TITLE
どきゅめんと

### ISSUE THREAD

**Issue by nownabe** [tojok-on/bts#1]
ローカルで実行できるようにもっと親切にかく

**Comment by kumamotone** [comment]
最近結構みんなMac持ってるし誰でもローカルにデプロイして使えるの素敵やん，となって説明書こうと思ったのですが，
ruby のバージョンの問題とか，そもそもhomebrew入ってない場合とか，まったく端末触ったこと無い人向けに書こうと思うとキリ無いなと思ったのでとりあえず一旦諦めました．

**Comment by nownabe** [comment]
:innocent: :+1:
